### ISSUE TITLE
Using meta['pre_dets'] before definition.

### ISSUE THREAD

**Issue by biubug6** [xingyizhou/CenterTrack#13]
Hi, I run 'python demo.py tracking --load_model ../models/coco_tracking.pth --demo /home/dl/img1/' and get below
Initialize tracking!
Traceback (most recent call last):
  File "demo.py", line 119, in <module>
    demo(opt)
  File "demo.py", line 90, in demo
    ret = detector.run(image_name)
  File "/home/dl/project/CenterTrack/src/lib/detector.py", line 93, in run
    self.tracker.init_track(meta['pre_dets'])
KeyError: 'pre_dets'

Obviously， it doesn't define meta['pre_dets'].

**Comment by xingyizhou** [comment]
It seems the current demo script does not support image folders. I will provide an updated one with this feature in the following days.

**Comment by esgnn** [comment]
I read a single image by open cv, still get the same error.
