### ISSUE TITLE
Problem with CUDA during training custom dataset

### ISSUE THREAD

**Issue by SimonSlominski** [xingyizhou/CenterTrack#132]
```
python main.py tracking --exp_id coco_tracking.sh --dataset custom --custom_dataset_ann_path ../data/mot17/annot
ations/train_half.json --custom_dataset_img_path ../data/mot17/train/ --input_h 1280 --input_w 960 --num_classes 1 --pre_hm --ltrb_amodal --same_aug --hm_disturb 0.05 --lost_disturb 0.4 --fp_disturb 0.1 --gpus 0,1

Running tracking
Using tracking threshold for out threshold! 0.3
Fix size testing.
training chunk_sizes: [16, 16]
input h w: 1280 960
heads {'hm': 1, 'reg': 2, 'wh': 2, 'tracking': 2, 'ltrb_amodal': 4}
weights {'hm': 1, 'reg': 1, 'wh': 0.1, 'tracking': 1, 'ltrb_amodal': 0.1}
head conv {'hm': [256], 'reg': [256], 'wh': [256], 'tracking': [256], 'ltrb_amodal': [256]}
Creating model...
Using node type: (<class 'model.networks.dla.DeformConv'>, <class 'model.networks.dla.DeformConv'>)
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    main(opt)
  File "main.py", line 58, in main
    trainer.set_device(opt.gpus, opt.chunk_sizes, opt.device)
  File "/media/CenterTrack/src/lib/trainer.py", line 114, in set_device
    chunk_sizes=chunk_sizes).to(device)
  File "/media/CenterTrack/src/lib/model/data_parallel.py", line 127, in DataParallel
    return torch.nn.DataParallel(module, device_ids, output_device, dim)
  File "/home/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 133, in __init__
    _check_balance(self.device_ids)
  File "/home/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 19, in _check_balance
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/home/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 19, in <listcomp>
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/home/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/cuda/__init__.py", line 328, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
```

I understand that there is no cuda device, but according to code in that case it should run with 'cpu'
`opt.device = torch.device('cuda' if opt.gpus[0] >= 0 else 'cpu')`

I've also checked the cuda info. Here are results:
__Python VERSION: 3.5.2 (default, Jul 17 2020, 14:04:10) [GCC 5.4.0 20160609]
__pyTorch VERSION: 1.2.0
__CUDA VERSION
__CUDNN VERSION: 7602
__Number CUDA Devices: 1
__Devices
index, name, driver_version, memory.total [MiB], memory.used [MiB], memory.free [MiB]
0, GeForce RTX 2080 Ti, 410.78, 10989 MiB, 523 MiB, 10466 MiB
Active CUDA Device: GPU 0
Available devices  1
Current cuda device  0

Any ideas how to solve that?

**Comment by manners-park** [comment]
--gpus 0,1 <-- -- gpu 0
