### ISSUE TITLE
No module named 'torchvision.models.utils

### ISSUE THREAD

**Issue by dyl25984** [xingyizhou/CenterTrack#134]
My torch version is 1.0.0 and torchvision version is 0.2.1.
When I run demo.py by using the command: 
python demo.py tracking,ddd --load_model ../models/nuScenes_3Dtracking.pth --dataset nuscenes --pre_hm --track_thresh 0.1 --demo ../videos/nuscenes_mini.mp4 --test_focal_length 633
It shows:
Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    from detector import Detector
  File "/home/user/CenterTrack/src/lib/detector.py", line 13, in <module>
    from model.model import create_model, load_model
  File "/home/user/CenterTrack/src/lib/model/model.py", line 14, in <module>
    from .networks.generic_network import GenericNetwork
  File "/home/user/CenterTrack/src/lib/model/networks/generic_network.py", line 9, in <module>
    from .backbones.mobilenet import MobileNetV2
  File "/home/user/CenterTrack/src/lib/model/networks/backbones/mobilenet.py", line 14, in <module>
    from torchvision.models.utils import load_state_dict_from_url
ModuleNotFoundError: No module named 'torchvision.models.utils'
How should I do to sovle this problem?

**Comment by wowkie83** [comment]
try pytorch 1.4. It worksfor me.

**Comment by zoeveryday** [comment]
same problem here.

My environment is:
python=3.6
pytorch=1.0.0
torchvision=0.2.1
cuda=10.0
cudnn=7

I setup my environment using the following command: 
```
# CUDA 10.0
conda install pytorch==1.0.0 torchvision==0.2.1 cuda100 -c pytorch
```
Still can't get the demo to run...

**Comment by wzwb** [comment]
Yes , my environment is same to you ,you can see what i said before.

**Comment by zoeveryday** [comment]
> Yes , my environment is same to you ,you can see what i said before.

Thanks for the reply. 
I was able to solve the problem by upgrading my pytorch version to 1.4, and torchvision to 0.5.0

Here is the command I used:
`pip install torch==1.4.0+cu100 torchvision==0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html`

My docker image is `nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04`

**Comment by chiranthancv95** [comment]
If using Higher version of Pytorch,
try replacing the line "from torchvision.models.utils import load_state_dict_from_url"
to
 "from torch.hub import load_state_dict_from_url"
This should work.
