### ISSUE TITLE
 Caught KeyError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by leejihyeok** [xingyizhou/CenterTrack#212]
i want to train by using coco data but it doesn't work 
the error is 

File "main.py", line 106, in <module>
    main(opt)
  File "main.py", line 73, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/jihyeok/Workspace/CenterTrack/src/lib/trainer.py", line 317, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/jihyeok/Workspace/CenterTrack/src/lib/trainer.py", line 141, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "/home/jihyeok/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/jihyeok/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/jihyeok/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/jihyeok/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jihyeok/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jihyeok/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jihyeok/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jihyeok/Workspace/CenterTrack/src/lib/dataset/generic_dataset.py", line 122, in __getitem__
    pre_anns, trans_input_pre, trans_output_pre)
  File "/home/jihyeok/Workspace/CenterTrack/src/lib/dataset/generic_dataset.py", line 213, in _get_pre_dets
    cls_id = int(self.cat_ids[ann['category_id']])
KeyError: 65

and my code is 
python main.py tracking --exp_id coco --tracking --dataset custom --gpus 0 --batch_size 28 --lr 1.25e-4 --num_workers 0 --pre_hm --shift 0.05 --scale 0.05 --hm_disturb 0.05 --lost_disturb 0.4 --fp_disturb 0.1 --custom_dataset_img_path /home/jihyeok/Datasets/coco/images/train2017/train2017 --custom_dataset_ann_path /home/jihyeok/Datasets/coco/annotations/instances_train2017.json --num_classes 2 --input_h 512 --input_w 512

How can i solve it?

**Comment by cheng-linkai** [comment]
Hi.Have you found the solution?Thank you in advance
