### ISSUE TITLE
Test script gives error with custom dataset paths , AttributeError: Caught AttributeError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by anshudaur** [xingyizhou/CenterTrack#220]
HI , I am not able to test the trained model on MOT dataset with custom paths, hence i am passing custom to be able to work with different paths:   

Command used
!python test.py tracking \
            --dataset custom \
            --custom_dataset_ann_path /home/CenterTrack_v1/annotations/test.json \
            --custom_dataset_img_path /datasets/MOT17/test/ \
            --load_model /home/CenterTrack_v1/models/mot_trained_model/model_last.pth \
            --pre_hm --ltrb_amodal --track_thresh 0.4 --pre_thresh 0.5 --input_h 544 --input_w 960 --num_classes 1 

==> initializing val data from /home/CenterTrack_v1/annotations/test.json, 
 images from /datasets/MOT17/test/ ...
loading annotations into memory...
Done (t=0.07s)
creating index...
index created!
Creating video index!
Loaded Custom dataset 15948 samples
Creating model...
Using node type: (<class 'model.networks.dla.DeformConv'>, <class 'model.networks.dla.DeformConv'>)
Warning: No ImageNet pretrain!!
loaded /home/CenterTrack_v1/models/mot_trained_model/model_last.pth, epoch 10
Drop parameter base.fc.weight.
Drop parameter base.fc.bias.
defaultTraceback (most recent call last):
  File "test.py", line 197, in <module>
    prefetch_test(opt)
  File "test.py", line 88, in prefetch_test
    for ind, (img_id, pre_processed_images) in enumerate(data_loader):
  File "/home/anaconda3/envs/torch1.7/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/anaconda3/envs/torch1.7/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/anaconda3/envs/torch1.7/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/anaconda3/envs/torch1.7/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/torch1.7/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/envs/torch1.7/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/torch1.7/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "test.py", line 40, in __getitem__
    else self.get_default_calib(image.shape[1], image.shape[0])
AttributeError: 'NoneType' object has no attribute 'shape'

Thank you for your help. 
Anshu

**Comment by MichiTrain** [comment]
did you solved it? i have a similar issue

**Comment by Valllls** [comment]
I was having the same issue when running test.py and it turned out that the error was due to the image test.py was looking for in the code snippet quoted didn't exist at the path being searched.

>  else self.get_default_calib(image.shape[1], image.shape[0])  

To resolve this the img_path variable from Ln34 of test.py could be printed to determine if an image with that path exists.
