### ISSUE TITLE
run demo.py on RTX3090 & GTX 980ti

### ISSUE THREAD

**Issue by Xuguozi** [xingyizhou/CenterTrack#230]
hi ,when i finished training a model, i run   'python demo.py' to load 'model_last.pth' on RTX3090 and GTX980 ti,respectively. 
Then, something happens:
On RTX3090, './Centertrack/results' is abnormal, the object of image hasn't tracking boxes;

![demo1](https://user-images.githubusercontent.com/89565268/131323351-6b0e2f02-f34c-4d80-8b57-87dede7f13fe.jpg)

but on GTX980 ti ,it's normal

![demo1](https://user-images.githubusercontent.com/89565268/131323665-2cc49e29-fcf6-42af-ae62-1a27600b3b19.jpg)

RTX3090 environment:
    cuda 11.1,  cudnn 8.2
    python 3.6, pytorch 1.7, torchvision 0.8.2

GTX980ti environment:
    cuda 9,  cudnn 7
    python 3.6, pytorch 1.4, torchvision 0.5.0
i wanna find out why,thanks for your help.

**Comment by unbeliveyu** [comment]
Hello, I would like to ask how you implemented it. My environment is windows rtx3060 cuda11.0 pytorch1.7.0 torchvision 0.8.0. There are many problems when compiling dcnv2. It is not friendly to 30 series graphics cards, and an error is reported when running demo
`error in modulated_deformable_im2col_cuda: no kernel image is available for execution on the device
error in modulated_deformable_im2col_cuda: no kernel image is available for execution on the device
error in modulated_deformable_im2col_cuda: no kernel image is available for execution on the device
error in modulated_deformable_im2col_cuda: no kernel image is available for execution on the device
error in modulated_deformable_im2col_cuda: no kernel image is available for execution on the device
Traceback (most recent call last):
  File "E:/github/CenterTrack/src/demo.py", line 128, in <module>
    demo(opt)
  File "E:/github/CenterTrack/src/demo.py", line 83, in demo
    ret = detector.run(img)
  File "E:\github\CenterTrack\src\lib\detector.py", line 119, in run
    images, self.pre_images, pre_hms, pre_inds, return_time=True)
  File "E:\github\CenterTrack\src\lib\detector.py", line 339, in process
    output = self.model(images, pre_images, pre_hms)[-1]
  File "D:\anaconda\envs\DCNv2\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\github\CenterTrack\src\lib\model\networks\base_model.py", line 75, in forward
    feats = self.imgpre2feats(x, pre_img, pre_hm)
  File "E:\github\CenterTrack\src\lib\model\networks\dla.py", line 633, in imgpre2feats
    x = self.dla_up(x)
  File "D:\anaconda\envs\DCNv2\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\github\CenterTrack\src\lib\model\networks\dla.py", line 572, in forward
    ida(layers, len(layers) -i - 2, len(layers))
  File "D:\anaconda\envs\DCNv2\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\github\CenterTrack\src\lib\model\networks\dla.py", line 543, in forward
    layers[i] = upsample(project(layers[i]))
  File "D:\anaconda\envs\DCNv2\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\anaconda\envs\DCNv2\lib\site-packages\torch\nn\modules\conv.py", line 929, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.`
