### ISSUE TITLE
failed to start training on crowdhuman dataset

### ISSUE THREAD

**Issue by heonwool** [xingyizhou/CenterTrack#246]
Hi,

I am currently trying to train crowdhuman dataset, not using your model_zoo implementation. However, when I use the same script in the experiment folder, it simply does not work!

I cannot find why the out_channel is considered as NoneType. I am sure that the environment set up correctly since training on 'crowdhuman.pth' does work.

Thanks!

guest@guest-desktop:~/CenterTrack/src$ python main.py tracking --exp_id crowdhuman --dataset crowdhuman --ltrb_amodal --pre_hm --shift 0.05 --scale 0.05 --hm_disturb 0.05 --lost_disturb 0.4 --fp_disturb 0.1 --num_epochs 140 --lr_step 90,120 --save_point 60,90 --gpus 0,1 --batch_size 64 --lr 2.5e-4 --num_workers 16
Running tracking
Using tracking threshold for out threshold! 0.3
Fix size testing.
training chunk_sizes: [32, 32]
input h w: 512 512
heads {'hm': None, 'reg': 2, 'wh': 2, 'tracking': 2, 'ltrb_amodal': 4}
weights {'hm': 1, 'reg': 1, 'wh': 0.1, 'tracking': 1, 'ltrb_amodal': 0.1}
head conv {'hm': [256], 'reg': [256], 'wh': [256], 'tracking': [256], 'ltrb_amodal': [256]}
Namespace(K=100, add_05=False, amodel_offset_weight=1, arch='dla_34', aug_rot=0, backbone='dla34', batch_size=64, chunk_sizes=[32, 32], custom_dataset_ann_path='', custom_dataset_img_path='', data_dir='/home/guest/CenterTrack/src/lib/../../data', dataset='crowdhuman', dataset_version='', debug=0, debug_dir='/home/guest/CenterTrack/src/lib/../../exp/tracking/crowdhuman/debug', debugger_theme='white', demo='', dense_reg=1, dep_weight=1, depth_scale=1, dim_weight=1, dla_node='dcn', down_ratio=4, efficient_level=0, eval_val=False, exp_dir='/home/guest/CenterTrack/src/lib/../../exp/tracking', exp_id='crowdhuman', fix_res=True, fix_short=-1, flip=0.5, flip_test=False, fp_disturb=0.1, gpus=[0, 1], gpus_str='0,1', head_conv={'hm': [256], 'reg': [256], 'wh': [256], 'tracking': [256], 'ltrb_amodal': [256]}, head_kernel=3, heads={'hm': None, 'reg': 2, 'wh': 2, 'tracking': 2, 'ltrb_amodal': 4}, hm_disturb=0.05, hm_hp_weight=1, hm_weight=1, hp_weight=1, hungarian=False, ignore_loaded_cats=[], input_h=512, input_res=512, input_w=512, keep_res=False, kitti_split='3dop', load_model='', load_results='', lost_disturb=0.4, lr=0.00025, lr_step=[90, 120], ltrb=False, ltrb_amodal=True, ltrb_amodal_weight=0.1, ltrb_weight=0.1, map_argoverse_id=False, master_batch_size=32, max_age=-1, max_frame_dist=3, model_output_list=False, msra_outchannel=256, neck='dlaup', new_thresh=0.3, nms=False, no_color_aug=False, no_pause=False, no_pre_img=False, non_block_test=False, not_cuda_benchmark=False, not_idaup=False, not_max_crop=False, not_prefetch_test=False, not_rand_crop=False, not_set_cuda_env=False, not_show_bbox=False, not_show_number=False, not_show_txt=False, num_classes=None, num_epochs=140, num_head_conv=1, num_iters=-1, num_layers=101, num_stacks=1, num_workers=16, nuscenes_att=False, nuscenes_att_weight=1, off_weight=1, only_show_dots=False, optim='adam', out_thresh=0.3, output_h=128, output_res=128, output_w=128, pad=31, pre_hm=True, pre_img=True, pre_thresh=0.3, print_iter=0, prior_bias=-4.6, public_det=False, qualitative=False, reg_loss='l1', reset_hm=False, resize_video=False, resume=False, reuse_hm=False, root_dir='/home/guest/CenterTrack/src/lib/../..', rot_weight=1, rotate=0, same_aug_pre=False, save_all=False, save_dir='/home/guest/CenterTrack/src/lib/../../exp/tracking/crowdhuman', save_framerate=30, save_img_suffix='', save_imgs=[], save_point=[60, 90], save_results=False, save_video=False, scale=0.05, seed=317, shift=0.05, show_trace=False, show_track_color=False, skip_first=-1, tango_color=False, task='tracking', test=False, test_dataset='crowdhuman', test_focal_length=-1, test_scales=[1.0], track_thresh=0.3, tracking=True, tracking_weight=1, trainval=False, transpose_video=False, use_kpt_center=False, use_loaded_results=False, val_intervals=10000, velocity=False, velocity_weight=1, video_h=512, video_w=512, vis_gt_bev='', vis_thresh=0.3, weights={'hm': 1, 'reg': 1, 'wh': 0.1, 'tracking': 1, 'ltrb_amodal': 0.1}, wh_weight=0.1, zero_pre_hm=False, zero_tracking=False)
fatal: No names found, cannot describe anything.
Creating model...
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    main(opt)
  File "main.py", line 40, in main
    model = create_model(opt.arch, opt.heads, opt.head_conv, opt=opt)
  File "/home/guest/CenterTrack/src/lib/model/model.py", line 28, in create_model
    model = model_class(num_layers, heads=head, head_convs=head_conv, opt=opt)
  File "/home/guest/CenterTrack/src/lib/model/networks/dla.py", line 597, in __init__
    heads, head_convs, 1, 64 if num_layers == 34 else 128, opt=opt)
  File "/home/guest/CenterTrack/src/lib/model/networks/base_model.py", line 29, in __init__
    kernel_size=1, stride=1, padding=0, bias=True)
  File "/home/guest/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 332, in __init__
    False, _pair(0), groups, bias, padding_mode)
  File "/home/guest/anaconda3/envs/CenterTrack/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 24, in __init__
    if out_channels % groups != 0:
TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'

**Comment by lt573152873** [comment]
num_classes is 1,  the result of  mot17 mota ?
