### ISSUE TITLE
No such file or directory: '../../data/mot17/train'

### ISSUE THREAD

**Issue by bryanbocao** [xingyizhou/CenterTrack#289]
```
*/CenterTrack/src/tools$ bash get_mot_17.sh
Traceback (most recent call last):
  File "convert_mot_to_coco.py", line 22, in <module>
    seqs = os.listdir(data_path)
FileNotFoundError: [Errno 2] No such file or directory: '../../data/mot17/train'
Traceback (most recent call last):
  File "convert_mot_det_to_results.py", line 14, in <module>
    os.mkdir(OUT_DIR)
FileNotFoundError: [Errno 2] No such file or directory: '../../data/mot17/results/'
```

**Comment by bryanbocao** [comment]
Fixed by
https://github.com/xingyizhou/CenterTrack/pull/290
https://github.com/xingyizhou/CenterTrack/pull/290/commits/a5543cfc9f9fadf9bf4d27cb4f7816982c2b289a
https://github.com/bryanbocao/CenterTrack/blob/master/src/tools/get_mot_17.sh
