### ISSUE TITLE
Warning: No ImageNet pretrain!!

### ISSUE THREAD

**Issue by BlackCutter** [xingyizhou/CenterTrack#29]
When I use `python demo.py tracking --load_model ../models/coco_tracking.pth --demo /path/to/image/or/folder/or/video,` I get the following error：
`D:\ProgramData\Anaconda3\envs\pytorch13\lib\site-packages\sklearn\utils\linear_assignment_.py:22: FutureWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)
Running tracking
Using tracking threshold for out threshold! 0.3
Fix size testing.
training chunk_sizes: [32]
input h w: 512 512
heads {'hm': 80, 'reg': 2, 'wh': 2, 'tracking': 2}
weights {'hm': 1, 'reg': 1, 'wh': 0.1, 'tracking': 1}
head conv {'hm': [256], 'reg': [256], 'wh': [256], 'tracking': [256]}
Creating model...
Using node type: (<class 'model.networks.dla.DeformConv'>, <class 'model.networks.dla.DeformConv'>)
Warning: No ImageNet pretrain!!
Traceback (most recent call last):
  File "demo.py", line 118, in <module>
    demo(opt)
  File "demo.py", line 23, in demo
    detector = Detector(opt)
  File "E:\Track3\CenterTrack\src\lib\detector.py", line 33, in __init__
    opt.arch, opt.heads, opt.head_conv, opt=opt)
  File "E:\Track3\CenterTrack\src\lib\model\model.py", line 28, in create_model
    model = model_class(num_layers, heads=head, head_convs=head_conv, opt=opt)
  File "E:\Track3\CenterTrack\src\lib\model\networks\dla.py", line 611, in __init__
    node_type=self.node_type)
  File "E:\Track3\CenterTrack\src\lib\model\networks\dla.py", line 564, in __init__
    node_type=node_type))
  File "E:\Track3\CenterTrack\src\lib\model\networks\dla.py", line 526, in __init__
    proj = node_type[0](c, o)
  File "E:\Track3\CenterTrack\src\lib\model\networks\dla.py", line 513, in __init__
    self.conv = DCN(chi, cho, kernel_size=(3,3), stride=1, padding=1, dilation=1, deformable_groups=1)
TypeError: 'NoneType' object is not callable
`
Is there anything wrong?
Thanks a lot!

**Comment by xingyizhou** [comment]
Hi,
  You need to replace `/path/to/image/or/folder/or/video` to the real path of your video. `Warning: No ImageNet pretrain!! ` doesn't matter because we already loaded a pretrained model and there is no need to use ImageNet pretrain.
