### ISSUE TITLE
subprocess.CalledProcessError: Command '['git', 'describe']' returned non-zero exit status 128.

### ISSUE THREAD

**Issue by JoeyQWu** [xingyizhou/CenterTrack#73]
Hi, 
Did anyone come across this error  when running the training command?
what should I do to solve this problem?
thank a lot !
`fatal: No names found, cannot describe anything.
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    main(opt)
  File "main.py", line 37, in main
    logger = Logger(opt)
  File "/home/ubuntu/CenterTrack/src/lib/logger.py", line 33, in __init__
    subprocess.check_output(["git", "describe"])))
  File "/home/ubuntu/.conda/envs/centerNet/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/ubuntu/.conda/envs/centerNet/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'describe']' returned non-zero exit status 128.`

**Comment by xingyizhou** [comment]
You can comment out the corresponding line in logger.py. It is used to dump the current git hash for debugging.

**Comment by Double-zh** [comment]
Solution: Open the subprocess.py file and enter line 355, change check=True to check=False
