### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.utils.linear_assignment_'

### ISSUE THREAD

**Issue by towster** [xingyizhou/CenterTrack#74]
I just setup new Ubuntu desktop and am getting an error after following installation instructions.

```
$ python demo.py tracking,ddd --load_model ../models/nuScenes_3Dtracking.pth --dataset nuscenes --pre_hm --track_thresh 0.1 --demo ../videos/nuscenes_mini.mp4 --test_focal_length 633
Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    from detector import Detector
  File "/home/robert/CenterTrack/src/lib/detector.py", line 20, in <module>
    from utils.tracker import Tracker
  File "/home/robert/CenterTrack/src/lib/utils/tracker.py", line 2, in <module>
    from sklearn.utils.linear_assignment_ import linear_assignment
ModuleNotFoundError: No module named 'sklearn.utils.linear_assignment_'
```
It was not a requirement but I did 'pip install sklearn_utils' thinking that was what was needed but I still get the same error. Version installed was sklearn-utils-0.0.15.

**Comment by aviator19941** [comment]
I got the same error. I think it's because the current version of scikit-learn 0.23.0 has removed linear_assignment_. I ran 'pip3 install scikit-learn==0.22.2' and I was able to run the demo after that.

**Comment by YoushaaMurhij** [comment]
!pip install scikit-learn==0.22.2
